templateVars = {
    'year':'2015',
#    'baml_logo':'http://www.ashanet.org/chicago/events/2015/marathon/index/assets/boa_chimar_h_rgb_1.jpg',
    'baml_logo':'https://scontent-ord.xx.fbcdn.net/hphotos-xpa1/t31.0-8/1495181_10152923331531645_4198555104746370160_o.jpg',
    'baml_marathon_head_line':'Bank of America Chicago Marathon',
    'baml_marathon_blurb':'The Bank of America Chicago Marathon is the pinnacle of achievement for elite athletes and everyday runners alike. ',
    #'asha_for_education_logo':'http://www.ashanet.org/chicago/events/2015/marathon/index/assets/ta2logo_800_1.gif',
    'asha_for_education_logo':'http://www.ashanet.org/uflorida/old/TeamAshaUF0.jpg',
    'asha_for_education':'',
    'asha_for_education_blurb':'Asha for Education is a secular organization dedicated to change in India by focusing on basic education in the belief that education is a critical requisite for socio-economic change.',
    'sample_logo':'',
    'sample_headline':'',
    'sample_blurb':'',
    'fundraiser_1':'Neena Majumdar',
    'fundraiser_1_url': 'http://s3.amazonaws.com/37assets/svn/765-default-avatar.png',
    'fundraiser_1_amount': '3,000 USD',
    'fundraiser_2':'Chandan Majumdar',
    'fundraiser_2_url': 'http://s3.amazonaws.com/37assets/svn/765-default-avatar.png',
    'fundraiser_2_amount': '2,000 USD',
    'fundraiser_3':'Neena 2',
    'fundraiser_3_url': 'http://s3.amazonaws.com/37assets/svn/765-default-avatar.png',
    'fundraiser_3_amount': '3,000 USD',
    'fundraiser_4':'Barak',
    'fundraiser_4_url': 'http://s3.amazonaws.com/37assets/svn/765-default-avatar.png',
    'fundraiser_4_amount': '5,000 USD',
    }
